package com.emudhra.emra.subscriber.enums;

public enum EmailType {
    CREATION_OF_NEW_USER(1),
    DEACTIVATING_USER(2),
    PASSWORD_RESET(3),
    SETUP_CERTIFICATE_LINK(4),
    RA_APPROVED(5),
    REVOCATION_REQUEST_INITIATION(6),
    CERTIFICATE_REVOKED(7),
    REVOCATION_REQUEST_REJECTED(8),
    SUSPENSION_REQUEST_INITIATION(9),
    CERTIFICATE_SUSPENDED(10),
    SUSPENSION_REQUEST_REJECTED(11),
    ACTIVATION_REQUEST_INITIATION(12),
    CERTIFICATE_ACTIVATED(13),
    ACTIVATION_REQUEST_REJECTED(14),
    APPLICATION_REJECTED(15),
    FORGOT_USERNAME(16),
    GENERATE_PASSWORD(17),
    RENEWAL_REMAINDER(18),
    EMAIL_VERIFICATION_LINK(19),
    DOMAIN_VERIFICATION_LINK(20),
    REQUEST_AUTHORIZER_VERIFICATION(21),
    EMAIL_OTP(22),
    DOWNLOAD_PIN(23),
    SUBSCRIBER_AGREEMENT_LINK(24),
    RAISE_QUERY(25),
    SETUP_SHARE_LINK(26);

    private int code;

    EmailType(int code) {
        this.code = code;
    }

    public int getCode() {
        return code;
    }
}
